### PR TITLE
Drop down menus not working when extension active

### LINKED ISSUE #2: Drop down menus not working when extension active
A few users have noticed this strange bug:

> Great idea for a plugin, I like it very much. However, it makes some dropdown menus in browser based tools like Jupyter Notebook not work, even when the plugin is not supposed to interfere with the web site, or activated. The problem was fixed when I uninstalled RussianGram.

> Extremely useful, but with Chrome 85.0.4183.83 causes many website menus to fail. So If you're supposed to be able click a menu and see a drop down list of options to choose - nothing happens when you click the menu. It's just dead. I confirmed this by all extensions, re-enabling one by one and then once RussianGram was enabled, menu problem resumed.

### PR DESCRIPTION
**Pull request by masterWeber**
Fixed #2

### CODE REVIEW

File: js/wholepage.js [hunk 1]
```diff
@@ -1,19 +1,65 @@
...
+
+    return collectedText;
+}
+
+function updateText(collectedText, tagList) {
+
+    forEachTextNode(tagList, function (node, uid) {
+        if (node.uid !== uid) {
+            alert('Oops, something went wrong. Please Try Again.\n\nThe RussianGram.com team.');
+            throw new Error('While waiting for a response from the server, the DOM was changed.');
```
Comment (bzaar) [inline js/wholepage.js:45]: On some websites this might be very common. I suggest updating whatever nodes we can and then displaying one message at the end saying "Some parts of the page have not been stress marked. Please try again."
